### ISSUE TITLE
Error when Sales Channels Feature is disabled

### ISSUE THREAD

**Issue by BeyondOT** [RSC-Labs/medusa-store-analytics#9] opened 2024-03-30 07:01 UTC
# Screenshot
![image](https://github.com/RSC-Labs/medusa-store-analytics/assets/65593661/4b774771-b505-4084-a31b-d88910eb63c3)

# Logs
```
::1 - - [30/Mar/2024:06:43:23 +0000] "GET /admin/customers-analytics/repeat-customer-rate?orderStatuses%5B0%5D=completed&orderStatuses%5B1%5D=pending&dateRangeFrom=1711234800000&dateRangeTo=1711781002805&dateRangeFromCompareTo=1710630000000&dateRangeToCompareTo=1711234800000 HTTP/1.1" 200 309 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
::1 - - [30/Mar/2024:06:43:23 +0000] "GET /admin/sales-analytics/regions-popularity?orderStatuses%5B0%5D=completed&orderStatuses%5B1%5D=pending&dateRangeFrom=1711234800000&dateRangeTo=1711781002805&dateRangeFromCompareTo=1710630000000&dateRangeToCompareTo=1711234800000 HTTP/1.1" 200 294 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
::1 - - [30/Mar/2024:06:43:23 +0000] "GET /admin/products-analytics/popularity-by-count?orderStatuses%5B0%5D=completed&orderStatuses%5B1%5D=pending&dateRangeFrom=1711234800000&dateRangeTo=1711781002805&dateRangeFromCompareTo=1710630000000&dateRangeToCompareTo=1711234800000 HTTP/1.1" 200 284 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
::1 - - [30/Mar/2024:06:43:23 +0000] "GET /uploads/1707380565149-meskini_olive.jpg HTTP/1.1" 304 - "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
::1 - - [30/Mar/2024:06:43:23 +0000] "GET /admin/products-analytics/sold-count?orderStatuses%5B0%5D=completed&orderStatuses%5B1%5D=pending&dateRangeFrom=1711234800000&dateRangeTo=1711781002805&dateRangeFromCompareTo=1710630000000&dateRangeToCompareTo=1711234800000 HTTP/1.1" 200 179 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
::1 - - [30/Mar/2024:06:43:23 +0000] "GET /admin/marketing-analytics/discounts-by-count?orderStatuses%5B0%5D=completed&orderStatuses%5B1%5D=pending&dateRangeFrom=1711234800000&dateRangeTo=1711781002805&dateRangeFromCompareTo=1710630000000&dateRangeToCompareTo=1711234800000 HTTP/1.1" 200 86 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
::1 - - [30/Mar/2024:06:43:23 +0000] "GET /admin/products-analytics/returned-by-count?dateRangeFrom=1711234800000&dateRangeTo=1711781002805&dateRangeFromCompareTo=1710630000000&dateRangeToCompareTo=1711234800000 HTTP/1.1" 200 86 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
error:   Relation with property path sales_channel in entity was not found.
TypeORMError: Relation with property path sales_channel in entity was not found.
    at JoinAttribute.getValue (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\typeorm\query-builder\JoinAttribute.js:109:23)
    at get relation [as relation] (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\typeorm\query-builder\JoinAttribute.js:111:53)
    at get metadata [as metadata] (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\typeorm\query-builder\JoinAttribute.js:122:18)
    at SelectQueryBuilder.join (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\typeorm\query-builder\SelectQueryBuilder.js:963:53)
    at SelectQueryBuilder.leftJoin (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\typeorm\query-builder\SelectQueryBuilder.js:195:14)
    at SelectQueryBuilder.leftJoinAndSelect (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\typeorm\query-builder\SelectQueryBuilder.js:215:14)  
    at SalesAnalyticsService.getSalesChannelsPopularity (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\@rsc-labs\medusa-store-analytics\dist\services\salesAnalytics.js:135:22)
    at GET (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\@rsc-labs\medusa-store-analytics\dist\api\admin\sales-analytics\[kind]\route.js:35:50)
    at C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\@medusajs\utils\dist\common\wrap-handler.js:57:42
    at step (C:\Users\Achra\Documents\Projets\koul-marketplace\koul-marketplace-backend\node_modules\@medusajs\utils\dist\common\wrap-handler.js:33:23)
::1 - - [30/Mar/2024:06:43:24 +0000] "GET /admin/sales-analytics/sales-channels-popularity?orderStatuses%5B0%5D=completed&orderStatuses%5B1%5D=pending&dateRangeFrom=1711234800000&dateRangeTo=1711781002805&dateRangeFromCompareTo=1710630000000&dateRangeToCompareTo=1711234800000 HTTP/1.1" 500 86 "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
::1 - - [30/Mar/2024:06:43:35 +0000] "GET /admin/auth HTTP/1.1" 304 - "http://localhost:7001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
```

# How it happened
I had just installed the plugin and ran the server, went to analytics and this error shows up.

# Possible cause
It's the fact that I have disabled sales channels that makes this issue happen. When I enable them again this issue goes away.

**Comment by radoslaw-sz** [comment] 2024-03-30 09:28
hi @BeyondOT  - thanks for raising this issue and possible cause, it is really helpful :) 
Indeed it can be a bug, I will fix it after Easter.

**Comment by radoslaw-sz** [comment] 2024-03-31 16:47
hi @BeyondOT  - fix is not yet ready, but I would like to inform that errors started to be handled gracefully. In other words, if one statistic failed, you can still see the others.

It might be useful if problematic statistics does not have high priority.

Improvement is available in version 0.10.3.

**Comment by radoslaw-sz** [comment] 2024-04-02 15:29
hi @BeyondOT  - unfortunately, I am trying to reproduce this issue but I cannot. I checked different scenarios, like disabling sales channel or removing it completely but still I do not get this error.
Could you please send me your raw order which is affected by disabled sales channel? You can find it in order details at very bottom. Of course please filter sensitive information, what I am curious is what you have under sales_channel key.
And could you please again describe your scenario? I mean did you have already some orders in your store and then install this plugin? Did you have already disabled sales channel after orders have been placed?

**Comment by BeyondOT** [comment] 2024-04-05 07:55
Hi @radoslaw-sz - I apologize for the late reply. 

I don't know which order exactly is causing the issue since i have 100+ orders. So I am going to try and describe better my situation.

## Architecture explanation:
- The medusa backend is used for the purpose of making a marketplace.
- There used to be a different sales channel for each new store that was created.
- Everytime an order is created by a customer, a child order is created for each different store included in this order. This child order contains all the infos of the parent order plus the store_id of the store where those products come from. ( This implementation by the way also shows "wrong" data when calculating the number of orders and number of sold products, I can make another issue about it but since it's specfic to my implementation I don't think it's relevant for the plugin )

## Situation explanation:
- I did have multiple orders before disabling the sales channels.
- I disabled the sales channels and made some orders.
- I then installed the plugin.
- The plugin works fine when sales channels are enabled but crashes when disabled.

**Comment by radoslaw-sz** [comment] 2024-04-05 18:10
hi @BeyondOT  - no worries, I am glad that you explained it so well.
However, I am afraid that we would need to focus more on your current architecture as it is something which might cause this issue.
I see you are making this "child order" and you mentioned that these "child orders" are also taken into account when statistics are generated (so that's why you have this misleading view). I start to think that maybe these "child orders" cause the issue - do you maybe properly create also relations between this child Order and Sales Channel? The error indicates that there is a problem to find a relation between Order and Sales Channel, while I was trying to play with normal orders and I cannot reproduce this issue...
Or maybe you are changing something in these relations in the orders?
This enabling/disabling sales channel is also interesting, that it has influence - the plugin itself does not care about it, so I trying to figure out how it might fix/break this scenario.

PS. Regarding this specific issue - yes, it sounds like it is very specific to your implementation and I am not sure if it something which others will see... However, if you feel that it will be very desired you can always raise an issue and I can tag it properly.

**Comment by BeyondOT** [comment] 2024-04-08 08:03
Hi @radoslaw-sz , this was indeed the issue. It's in the relation between these child orders and sales channels. It seems like I forgot to pass the sales channel id to the child orders when creating them. 

Regarding the duplicate orders and products sold, I will open an other issue like you said.

Thank you for your help with the issue.

**Comment by radoslaw-sz** [comment] 2024-04-08 15:08
hi @BeyondOT  - thanks, then I am closing this issue.

**Closed as completed by radoslaw-sz** 2024-04-08 15:08 UTC
